### ISSUE TITLE
use_case_1 bug

### ISSUE THREAD

**Issue by star20174154** [AICPS/roadscene2vec#6]
When I run use_case_1.py, the following error appears, what is the problem?
/home/lcx/anaconda3/envs/av3/bin/python /home/lcx/PycharmProjects/roadscene2vec-main/examples/use_case_1.py
0it [00:00, ?it/s]
0it [00:00, ?it/s]
- finished

**Comment by malawada** [comment]
Hello, are you sure that the path where you downloaded the dataset is configured correctly? This might happen if the path its searching is an empty folder.

**Comment by hkaeley** [comment]
Apologies for the late response, but also make sure you have downloaded all the contents of the use_case_data directory that we linked here: https://drive.google.com/drive/u/2/folders/15Wvwh1k7ySr2YW6ZRDxnpcQOpMe3J5F1 in the Usage Examples section of the project ReadMe. I have updated the lanechange folder in this directory, and I suspect your issue lies there.
